server:
  host: "0.0.0.0"
  port: "8080"

redis:
  db: 0
  auth:
  host: "0.0.0.0"
  port: "6379"
  type: "tcp"
  max_idle: 3
  max_active: 0 # on-demand allocation
  idle_timeout: 300 # sec (= 5 minutes)